[tool.ruff]
# This pyproject.toml file exists in my local system
# You have to remove/comment this, if you are using `ruff` in your project
# or, you can provide your own global config file path.
extend = "~/Developer/pyproject.toml"

target-version = "py310" # However, I am using python-3.11

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]
